services:
  dbserver:
    image: mysql:5.7
    container_name: carpark_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: carpark_db
      MYSQL_USER: carpark_db
      MYSQL_PASSWORD: Password123
    ports:
      - "3336:3306"
    volumes:
      - ./tmp/mysql:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 10s
      interval: 1s
      timeout: 1s
      retries: 10
    restart: on-failure
  cache:
    image: redis:latest
    container_name: carpark_cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save "" --loglevel warning --requirepass Password123
    volumes: 
      - ./cache:/data